# Generated by Django 6.0.3 on 2026-03-24 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0003_remove_emprestimo_usuario_emprestimo_nome_pessoa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=100)),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('previsao_devolucao', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_emprestimo', to='cadastro.livro')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
