# Generated by Django 6.0.3 on 2026-03-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('codigo', models.PositiveIntegerField()),
                ('quantidade_total', models.PositiveIntegerField()),
                ('quantidade_disponivel', models.PositiveIntegerField()),
                ('localizacao', models.CharField(max_length=20)),
                ('idioma', models.CharField(max_length=20)),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.editora')),
            ],
        ),
    ]
