# Generated by Django 6.0.3 on 2026-03-20 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('numero_carterinha', models.CharField(max_length=20)),
                ('tipo_usuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('previsao_devolucao', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario')),
            ],
        ),
    ]
