# Generated by Django 6.0.3 on 2026-03-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_usuario_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='nome_pessoa',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
