# Generated by Django 6.0.3 on 2026-03-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_emprestimo_nome_pessoa_remove_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
