# Generated by Django 6.0.3 on 2026-04-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_livro_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('E', 'Emprestado'), ('D', 'Devolvido'), ('A', 'Atrasado')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='codigo',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
