# Generated by Django 6.0.3 on 2026-04-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_emprestimo_status_livro_descricao_alter_livro_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
